apiVersion: skaffold/v2alpha3
kind: Config
deploy: # Start and stop the cluster using the specified deployments
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local: # When we make a change to the code, skaffold will automatically push the change to docker hub. We disabled this feature
    push: false
  artifacts: #Syncs changes to the cluster
    - image: michielswaanen/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: michielswaanen/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: michielswaanen/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: michielswaanen/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: michielswaanen/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: michielswaanen/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .